# 🚀 High-Frequency Delta-Neutral Bot Configuration
# Optimized for Maximum Volume Generation with Delta-Neutral Hedging

# Backpack API Configuration
api:
  base_url: "https://api.backpack.exchange"
  key: ${BACKPACK_API_KEY}
  secret: ${BACKPACK_API_SECRET}
  testnet: false
  
  # High-frequency rate limits
  rate_limits:
    requests_per_second: 100  # High-frequency trading
    orders_per_second: 20
    websocket_connections: 10
    
# SOL Collateral Strategy (Enhanced for HF)
sol_collateral:
  starting_amount: 1.0  # 1 SOL
  
  # Aggressive collateral utilization for volume
  collateral_utilization_target: 0.85  # 85% utilization
  max_collateral_ratio: 0.95  # 95% max
  emergency_buffer: 0.10  # 10% buffer
  
  # Auto lending (reduced for more trading capital)
  auto_lending:
    enabled: true
    lending_percentage: 0.40  # 40% (reduced from 60%)
    min_lending_apy: 0.02
    dynamic_rebalancing: true
    
# High-Frequency Trading Parameters
high_frequency:
  # Ultra-fast execution intervals
  grid_update_interval: 5  # 5 seconds
  rebalance_interval: 15  # 15 seconds
  funding_check_interval: 60  # 1 minute
  arbitrage_scan_interval: 10  # 10 seconds
  
  # Volume optimization
  volume_target: 100000  # $100k daily
  transaction_target: 3000  # 3k transactions daily
  volume_per_collateral_target: 1000  # 1000x leverage on volume
  
  # Market making parameters
  market_making:
    enabled: true
    spread_capture: 0.0005  # 0.05% spread
    order_refresh_rate: 3  # 3 seconds
    inventory_management: true
    
# Delta-Neutral Configuration
delta_neutral:
  enabled: true
  
  # Delta management
  target_delta: 0.0  # Perfect neutrality
  delta_tolerance: 0.02  # 2% tolerance
  rebalance_threshold: 0.015  # 1.5% triggers rebalance
  
  # Hedging strategy
  hedging:
    hedge_ratio: 1.0  # 1:1 hedging
    hedge_instrument: "futures"  # Use futures for hedging
    auto_hedge_enabled: true
    hedge_update_frequency: 15  # 15 seconds
    
  # Position management
  position_limits:
    max_spot_exposure: 0.25  # 25% per pair
    max_futures_exposure: 0.25  # 25% per pair
    max_total_delta: 0.05  # 5% max total delta
    
# Multi-Asset Grid Trading (HF Optimized)
grid_trading:
  pairs:
    - symbol: "SOL_USDC"
      allocation: 0.30  # 30%
      grid_levels: 40  # More levels for HF
      grid_spacing: 0.002  # 0.2% tight spacing
      min_order_size: 0.01
      max_position_size: 0.25
      hf_enabled: true
      
    - symbol: "BTC_USDC"
      allocation: 0.25  # 25%
      grid_levels: 35
      grid_spacing: 0.0015  # 0.15% very tight
      min_order_size: 0.0001
      max_position_size: 0.25
      hf_enabled: true
      
    - symbol: "ETH_USDC"
      allocation: 0.25  # 25%
      grid_levels: 35
      grid_spacing: 0.0018  # 0.18%
      min_order_size: 0.001
      max_position_size: 0.25
      hf_enabled: true
      
    - symbol: "USDT_USDC"
      allocation: 0.20  # 20%
      grid_levels: 100  # Many levels for stablecoin
      grid_spacing: 0.0002  # 0.02% ultra tight
      min_order_size: 1.0
      max_position_size: 0.50
      hf_enabled: true
  
  # HF Grid optimization
  optimization:
    adaptive_spacing: true
    volatility_adjustment: true
    volume_optimization: true
    spread_optimization: true
    
# Funding Rate Arbitrage
funding_arbitrage:
  enabled: true
  
  # Funding rate thresholds
  min_funding_rate: 0.0005  # 0.05% threshold
  target_funding_rate: 0.002  # 0.2% target
  max_funding_rate: 0.01  # 1% max
  
  # Position management
  position_sizing:
    base_size: 0.1  # 10% of collateral
    max_funding_exposure: 0.5  # 50% max in funding positions
    dynamic_sizing: true
    
  # Funding optimization
  optimization:
    position_flipping: true  # Flip for negative funding
    funding_prediction: true
    multi_pair_optimization: true
    
# Cross-Pair Arbitrage
cross_pair_arbitrage:
  enabled: true
  
  # Arbitrage parameters
  min_profit_threshold: 0.0005  # 0.05% minimum profit
  max_execution_time: 5  # 5 seconds max
  slippage_tolerance: 0.001  # 0.1% slippage
  
  # Supported triangular pairs
  triangular_pairs:
    - ["SOL_USDC", "BTC_USDC", "SOL_BTC"]
    - ["ETH_USDC", "BTC_USDC", "ETH_BTC"]
    - ["USDT_USDC", "SOL_USDC", "SOL_USDT"]
    
# Volume Generation Strategies
volume_generation:
  # Volume boosting techniques
  techniques:
    ping_pong_trading: true
    micro_arbitrage: true
    spread_capture: true
    inventory_rotation: true
    
  # Volume targets
  targets:
    hourly_volume: 4167  # $4167/hour for $100k daily
    transaction_frequency: 125  # 125 transactions/hour
    average_transaction_size: 33  # $33 average
    
  # Volume optimization
  optimization:
    peak_hours_boost: true
    fee_tier_optimization: true
    competitor_analysis: true
    
# Competition Strategy
competition:
  # Competition phases
  phases:
    establishment:  # Week 1
      volume_target: 75000  # $75k daily
      transaction_target: 2000
      risk_level: "conservative"
      
    acceleration:  # Week 2-3
      volume_target: 125000  # $125k daily
      transaction_target: 4000
      risk_level: "aggressive"
      
    sprint:  # Week 4
      volume_target: 200000  # $200k daily
      transaction_target: 6000
      risk_level: "maximum"
      
  # Competition optimization
  optimization:
    volume_rank_target: 5  # Top 5 volume
    pnl_rank_target: 3  # Top 3 PnL
    adaptive_strategy: true
    real_time_adjustment: true
    
# Risk Management (HF Adapted)
risk_management:
  # Position limits
  position_limits:
    max_position_per_pair: 0.25  # 25%
    max_total_exposure: 0.90  # 90% for HF
    max_delta_exposure: 0.05  # 5% max delta
    
  # High-frequency risk controls
  hf_risk_controls:
    max_drawdown: 0.08  # 8% max drawdown
    max_daily_loss: 0.03  # 3% daily loss limit
    velocity_limits: true
    correlation_monitoring: true
    
  # Emergency procedures
  emergency:
    auto_stop_loss: true
    position_reduction_threshold: 0.05  # 5% loss
    emergency_liquidation: 0.10  # 10% loss
    
# Performance Monitoring
performance:
  # Real-time metrics
  real_time_metrics:
    - volume_per_second
    - transaction_count
    - delta_exposure
    - collateral_utilization
    - funding_income
    - pnl_tracking
    
  # HF performance tracking
  hf_metrics:
    - execution_speed
    - order_fill_rate
    - spread_capture_rate
    - volume_efficiency
    - capital_turnover
    
  # Reporting
  reporting:
    real_time_dashboard: true
    minute_updates: true
    hourly_summaries: true
    competition_tracking: true
    
# Advanced Features
advanced:
  # Machine learning
  ml_features:
    enabled: false  # Disabled for initial version
    pattern_recognition: false
    predictive_modeling: false
    
  # AI optimization
  ai_optimization:
    enabled: false
    reinforcement_learning: false
    genetic_algorithms: false
    
  # Professional features
  professional:
    market_microstructure: true
    order_flow_analysis: true
    latency_optimization: true
    
# Monitoring and Alerts
monitoring:
  # High-frequency monitoring
  hf_monitoring:
    enabled: true
    update_frequency: 1  # 1 second
    alert_thresholds:
      high_delta: 0.03  # 3%
      high_volume_deviation: 0.20  # 20%
      low_funding_income: -0.001  # -0.1%
      
  # Competition monitoring
  competition_monitoring:
    ranking_updates: 300  # 5 minutes
    performance_alerts: true
    competitor_analysis: true
    
# Logging (HF Optimized)
logging:
  level: "INFO"
  file: "logs/backpack_hf_delta_neutral.log"
  max_size: 100MB  # Larger for HF
  backup_count: 20
  
  # HF specific logging
  hf_logging:
    trade_execution: true
    delta_rebalancing: true
    funding_events: true
    volume_milestones: true
    
# Expected Performance Targets
performance_targets:
  # Volume targets (Enhanced)
  volume_targets:
    daily_volume: 100000  # $100k daily (2x increase)
    hourly_volume: 4167   # $4167/hour
    peak_hour_volume: 8333  # $8333 peak hour
    volume_rank_target: 5  # Top 5
    
  # Transaction targets
  transaction_targets:
    daily_transactions: 3000  # 3k daily (3x increase)
    hourly_transactions: 125  # 125/hour
    peak_hour_transactions: 250  # 250 peak hour
    
  # PnL targets
  pnl_targets:
    daily_return: 0.012  # 1.2% daily (50% increase)
    funding_return: 0.008  # 0.8% from funding
    grid_return: 0.004  # 0.4% from grid
    monthly_return: 0.36  # 36% monthly
    pnl_rank_target: 3  # Top 3
    
  # Risk targets
  risk_targets:
    max_daily_drawdown: 0.02  # 2%
    max_delta_exposure: 0.05  # 5%
    sharpe_ratio_target: 3.0  # 3.0 Sharpe
    win_rate_target: 0.70  # 70% win rate
    
  # Efficiency targets
  efficiency_targets:
    volume_per_collateral: 1000  # 1000x
    capital_turnover: 50  # 50x daily
    execution_efficiency: 0.95  # 95% fill rate
    spread_capture_rate: 0.80  # 80% spread capture
